-- MySQL Script generated by MySQL Workbench
-- Sex 24 Jun 2016 19:34:25 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ruSql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ruSql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ruSql` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ruSql` ;

-- -----------------------------------------------------
-- Table `ruSql`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Modalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Vinculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Credito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Consumidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `grr` VARCHAR(11) NULL,
  `Modalidade_id` INT NULL,
  `Vinculo_id` INT NULL,
  `Credito_id` INT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Consumidor_Modalidade_idx` (`Modalidade_id` ASC),
  INDEX `fk_Consumidor_Vinculo1_idx` (`Vinculo_id` ASC),
  INDEX `fk_Consumidor_Credito1_idx` (`Credito_id` ASC),
  CONSTRAINT `fk_Consumidor_Modalidade`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Consumidor_Vinculo1`
    FOREIGN KEY (`Vinculo_id`)
    REFERENCES `ruSql`.`Vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Consumidor_Credito1`
    FOREIGN KEY (`Credito_id`)
    REFERENCES `ruSql`.`Credito` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`VinculosBloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`VinculosBloqueados` (
  `Vinculo_id` INT NOT NULL,
  `Modalidade_id` INT NOT NULL,
  PRIMARY KEY (`Vinculo_id`, `Modalidade_id`),
  INDEX `fk_VinculosBloqueados_Modalidade1_idx` (`Modalidade_id` ASC),
  CONSTRAINT `fk_VinculosBloqueados_Vinculo1`
    FOREIGN KEY (`Vinculo_id`)
    REFERENCES `ruSql`.`Vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VinculosBloqueados_Modalidade1`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `precoPadrao` DOUBLE NOT NULL,
  `precoVenda` DOUBLE NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`TaxaSubsidio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`TaxaSubsidio` (
  `Modalidade_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `taxaSubsidio` DOUBLE NULL,
  PRIMARY KEY (`Modalidade_id`, `Produto_id`),
  INDEX `fk_TaxaSubsidio_Modalidade1_idx` (`Modalidade_id` ASC),
  INDEX `fk_TaxaSubsidio_Produto1_idx` (`Produto_id` ASC),
  CONSTRAINT `fk_TaxaSubsidio_Modalidade1`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxaSubsidio_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `ruSql`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
