-- MySQL Script generated by MySQL Workbench
-- Qua 29 Jun 2016 04:14:40 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ruSql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ruSql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ruSql` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ruSql` ;

-- -----------------------------------------------------
-- Table `ruSql`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Modalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Vinculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Credito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Consumidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `grr` VARCHAR(11) NULL,
  `Modalidade_id` INT NULL,
  `Vinculo_id` INT NULL,
  `Credito_id` INT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Consumidor_Modalidade_idx` (`Modalidade_id` ASC),
  INDEX `fk_Consumidor_Vinculo1_idx` (`Vinculo_id` ASC),
  INDEX `fk_Consumidor_Credito1_idx` (`Credito_id` ASC),
  CONSTRAINT `fk_Consumidor_Modalidade`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Consumidor_Vinculo1`
    FOREIGN KEY (`Vinculo_id`)
    REFERENCES `ruSql`.`Vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Consumidor_Credito1`
    FOREIGN KEY (`Credito_id`)
    REFERENCES `ruSql`.`Credito` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`VinculosBloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`VinculosBloqueados` (
  `Vinculo_id` INT NOT NULL,
  `Modalidade_id` INT NOT NULL,
  PRIMARY KEY (`Vinculo_id`, `Modalidade_id`),
  INDEX `fk_VinculosBloqueados_Modalidade1_idx` (`Modalidade_id` ASC),
  CONSTRAINT `fk_VinculosBloqueados_Vinculo1`
    FOREIGN KEY (`Vinculo_id`)
    REFERENCES `ruSql`.`Vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VinculosBloqueados_Modalidade1`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `precoPadrao` DOUBLE NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`TaxaSubsidio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`TaxaSubsidio` (
  `Modalidade_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `taxaSubsidio` DOUBLE NULL,
  PRIMARY KEY (`Modalidade_id`, `Produto_id`),
  INDEX `fk_TaxaSubsidio_Modalidade1_idx` (`Modalidade_id` ASC),
  INDEX `fk_TaxaSubsidio_Produto1_idx` (`Produto_id` ASC),
  CONSTRAINT `fk_TaxaSubsidio_Modalidade1`
    FOREIGN KEY (`Modalidade_id`)
    REFERENCES `ruSql`.`Modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxaSubsidio_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `ruSql`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Checkin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Consumidor_id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Checkin_Consumidor1_idx` (`Consumidor_id` ASC),
  CONSTRAINT `fk_Checkin_Consumidor1`
    FOREIGN KEY (`Consumidor_id`)
    REFERENCES `ruSql`.`Consumidor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`TipoDeReceita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`TipoDeReceita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `credito` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`Venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Checkin_id` INT NOT NULL,
  `TipoDeReceita_id` INT NOT NULL,
  `Caixa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Venda_Checkin1_idx` (`Checkin_id` ASC),
  INDEX `fk_Venda_TipoDeReceita1_idx` (`TipoDeReceita_id` ASC),
  INDEX `fk_Venda_Caixa1_idx` (`Caixa_id` ASC),
  CONSTRAINT `fk_Venda_Checkin1`
    FOREIGN KEY (`Checkin_id`)
    REFERENCES `ruSql`.`Checkin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_TipoDeReceita1`
    FOREIGN KEY (`TipoDeReceita_id`)
    REFERENCES `ruSql`.`TipoDeReceita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Caixa1`
    FOREIGN KEY (`Caixa_id`)
    REFERENCES `ruSql`.`Caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`VendaItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`VendaItem` (
  `Venda_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `qtd` INT NOT NULL DEFAULT 1,
  `precoUnit` DOUBLE NOT NULL,
  PRIMARY KEY (`Venda_id`, `Produto_id`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_id` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_id`)
    REFERENCES `ruSql`.`Venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `ruSql`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruSql`.`CreditoCaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruSql`.`CreditoCaixa` (
  `Credito_id` INT NOT NULL,
  `Caixa_id` INT NOT NULL,
  `valor` DOUBLE NULL,
  `inserir` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`Credito_id`, `Caixa_id`),
  INDEX `fk_Credito_has_Caixa_Caixa1_idx` (`Caixa_id` ASC),
  INDEX `fk_Credito_has_Caixa_Credito1_idx` (`Credito_id` ASC),
  CONSTRAINT `fk_Credito_has_Caixa_Credito1`
    FOREIGN KEY (`Credito_id`)
    REFERENCES `ruSql`.`Credito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Credito_has_Caixa_Caixa1`
    FOREIGN KEY (`Caixa_id`)
    REFERENCES `ruSql`.`Caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
